version: '3'

services:

  tech-fiap-predict-service-train:
    hostname: tech-fiap-predict-service-service-train
    extends:
      file: predict-service/docker-compose.yml
      service: train
    network_mode: host

  tech-fiap-predict-service:
    hostname: tech-fiap-predict-service-service
    extends:
      file: predict-service/docker-compose.yml
      service: app
    network_mode: host

  tech-fiap-frontend:
    hostname: tech-fiap-frontend-service
    extends:
      file: streamlit-insurance-app/docker-compose.yml
      service: web
    network_mode: host